version: '2'

services:
  ubuntu-python36:
    build:
      context: .
    ports:
      - "8000:8000"
    command: /start-dev.sh
    volumes:
      - ./manage.py:/app/manage.py
      - ./requirements.txt:/app/requirements.txt
      - ./tipster:/app/tipster
      - ./spider:/app/spider
      - django_packages:/usr/local/lib/python3.6/site-packages/

volumes:
  django_packages: {}
