version: '2.1'

volumes:
  django_sample_db_dev: {}
  django_sample_packages: {}

services:
  db:
    image: postgres:9.6.1
    volumes:
      - django_sample_db_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=sampleuser
      - POSTGRES_PASSWORD=samplesecret
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -U postgres"
      interval: 3s
      timeout: 1s
      retries: 10

  httpbin:
    image: vimagick/httpbin
    restart: always
    ports:
      - "80"

  selenium:
    image: selenium/hub
    depends_on:
      httpbin:
        condition: service_started
    links:
      - httpbin:httpbin
    ports:
      - "4444"

#  phantomjs:
#    build:
#      context: .
#      dockerfile: ./compose/phantomjs/Dockerfile
#    depends_on:
#      selenium:
#        condition: service_started
#      httpbin:
#        condition: service_started
#    links:
#      - selenium:selenium
#      - httpbin:httpbin

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=postgres
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=sampledb
      - DJANGO_DB_USERNAME=sampleuser
      - DJANGO_DB_PASSWORD=samplesecret
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      selenium:
        condition: service_started
    links:
      - db:postgres
      - selenium:selenium
    command: /start-dev.sh
    volumes:
      - ./:/app/
      - ./manage.py:/app/manage.py
      - ./requirements.txt:/app/requirements.txt
      - ./djangosample:/app/djangosample
      - django_sample_packages:/usr/local/lib/python3.6/site-packages/

#  tester:
#    build:
#      context: .
#      dockerfile: ./compose/phantomjs
#    command: py.phantomjs phantomjs.py
#    depends_on:
#      selenium:
#        condition: service_started
#      phantomjs:
#        condition: service_started
